In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
#from wordcloud import WordCloud

In [2]:
df = pd.read_csv("C:/jupyternotebook/spam.csv",encoding = "ISO-8859-1")

In [3]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],inplace=True)

In [5]:
df.columns = ["labels",'data']

In [6]:
df.head()

labels                                               data
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df["b_labels"] = df["labels"].map({"ham":0,"spam":1})

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   labels    5572 non-null   object
 1   data      5572 non-null   object
 2   b_labels  5572 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 130.7+ KB


In [9]:
y=df["b_labels"].to_numpy()

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df["data"], y, test_size=0.33, random_state=42)


In [16]:
y_test

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [12]:
featurizer = CountVectorizer()

X_train = featurizer.fit_transform(X_train)
X_test = featurizer.transform(X_test)

In [24]:
from sklearn.naive_bayes import MultinomialNB
model_naivebase = MultinomialNB()
model_naivebase.fit(X_train,y_train)
print(model_naivebase.score(X_train,y_train))
print(model_naivebase.score(X_test,y_test))

0.994910259844629
0.9825992387166939


In [11]:
X_train

3235    Aight text me when you're back at mu and I'll ...
945     I cant wait to see you! How were the photos we...
5319                         Kothi print out marandratha.
5528    Its just the effect of irritation. Just ignore it
247                       Kallis wont bat in 2nd innings.
                              ...                        
3772    I came hostel. I m going to sleep. Plz call me...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860                   In work now. Going have in few min.
Name: data, Length: 3733, dtype: object

In [13]:
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [14]:
from sklearn.metrics import classification_report,confusion_matrix

In [15]:
model_linear_svc = LinearSVC()
model_linear_svc.fit(X_train,y_train)
print(model_linear_svc.score(X_test,y_test))
y_predicted = model_linear_svc.predict(X_test)
print(classification_report(y_test,y_predicted))
print(confusion_matrix(y_test,y_predicted))

0.9815116911364872
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1587
           1       0.99      0.87      0.93       252

    accuracy                           0.98      1839
   macro avg       0.99      0.94      0.96      1839
weighted avg       0.98      0.98      0.98      1839

[[1585    2]
 [  32  220]]


In [16]:
model_linear_svc = DecisionTreeClassifier()
model_linear_svc.fit(X_train,y_train)
print(model_linear_svc.score(X_test,y_test))
y_predicted = model_linear_svc.predict(X_test)
print(classification_report(y_test,y_predicted))
print(confusion_matrix(y_test,y_predicted))

0.9630233822729745
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1587
           1       0.86      0.87      0.87       252

    accuracy                           0.96      1839
   macro avg       0.92      0.93      0.92      1839
weighted avg       0.96      0.96      0.96      1839

[[1551   36]
 [  32  220]]


In [17]:
model_linear_svc = RandomForestClassifier()
model_linear_svc.fit(X_train,y_train)
print(model_linear_svc.score(X_test,y_test))
y_predicted = model_linear_svc.predict(X_test)
print(classification_report(y_test,y_predicted))
print(confusion_matrix(y_test,y_predicted))

0.9749864056552474
              precision    recall  f1-score   support

           0       0.97      1.00      0.99      1587
           1       1.00      0.82      0.90       252

    accuracy                           0.97      1839
   macro avg       0.98      0.91      0.94      1839
weighted avg       0.98      0.97      0.97      1839

[[1586    1]
 [  45  207]]


In [19]:
from sklearn.linear_model import LogisticRegression
model_linear_svc = LogisticRegression()
model_linear_svc.fit(X_train,y_train)
print(model_linear_svc.score(X_test,y_test))
y_predicted = model_linear_svc.predict(X_test)
print(classification_report(y_test,y_predicted))
print(confusion_matrix(y_test,y_predicted))

0.9787928221859706
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1587
           1       0.99      0.86      0.92       252

    accuracy                           0.98      1839
   macro avg       0.98      0.93      0.95      1839
weighted avg       0.98      0.98      0.98      1839

[[1584    3]
 [  36  216]]
